# Generated by Django 5.0.3 on 2024-04-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0003_registration_calory_needed_registration_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='age',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='gender',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
