# Generated by Django 5.0.3 on 2024-04-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0004_registration_age_registration_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='bmr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='life_style',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
