# Generated by Django 5.0.3 on 2024-04-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0006_diet_foods'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet_foods',
            name='current_needed_calory',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
