# Generated by Django 5.0.3 on 2024-04-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0007_diet_foods_current_needed_calory'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet_foods',
            name='carbohydrates_needed',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='diet_foods',
            name='fat_needed',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='diet_foods',
            name='fibre_needed',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='diet_foods',
            name='protein_needed',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='diet_foods',
            name='quantity_needed',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
