# Generated by Django 5.0.3 on 2024-04-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0008_diet_foods_carbohydrates_needed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
