# Generated by Django 5.0.3 on 2024-04-05 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0009_registration_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message_content', models.TextField(null=True)),
                ('From_reg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_message', to='foodapp.registration')),
                ('To_reg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_message', to='foodapp.registration')),
            ],
        ),
    ]
