# Generated by Django 5.0.4 on 2024-04-17 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0010_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch_messages', models.CharField(max_length=600, null=True)),
                ('ch_messages_reg_pat', models.CharField(max_length=200, null=True)),
                ('ch_messages_reg_pat1', models.CharField(max_length=200, null=True)),
                ('from_person', models.CharField(max_length=200, null=True)),
                ('ch_msg_doc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_doctor', to='foodapp.registration')),
                ('ch_msg_reg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_patient', to='foodapp.registration')),
            ],
        ),
        migrations.CreateModel(
            name='Live_doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liv_dr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foodapp.registration')),
            ],
        ),
    ]
